export const NOTICIAS_MOCK = [
  {
    slug: "tendencias-moda-2026-vogue",
    title: "Tendências de Moda Feminina no Brasil 2026: O Que Usar",
    categoria: "Estilo e Beleza",
    subcategoria: "Moda",
    data: "2026-08-01",
    autor: "Lillith Nogah",
    descricao: "Vogue Brasil antecipou: cores sofisticadas, tecidos nobres e moda consciente dominam 2026.",
    urlSite: "https://bemmaisbella.com.br/estilo-e-beleza/moda/tendencias-2026",
    urlFacebook: "https://facebook.com/bemmaisbella/posts/vogue-2026",
    urlInstagram: "https://instagram.com/p/vogue2026/",
    urlTikTok: "https://tiktok.com/@bemmaisbella/video/vogue2026",
    urlPinterest: "https://pinterest.com/pin/vogue2026",
    palavraChave: "tendencias moda feminina 2026",
    metaDescription: "As principais tendências de moda feminina no Brasil para 2026 — cores, tecidos nobres, moda consciente.",
    status: "Publicado",
  },
  {
    slug: "saude-feminina-2026-cartacapital",
    title: "Saúde Feminina em 2026: 10 Cuidados Essenciais",
    categoria: "Saúde e Bem-Estar",
    subcategoria: "Saúde",
    data: "2026-08-02",
    autor: "Lillith Nogah",
    descricao: "Carta Capital destaca cuidados essenciais: prevenção, saúde mental, nutrição, autocuidado.",
    urlSite: "https://bemmaisbella.com.br/saude-e-bem-estar/saude/cuidados-2026",
    urlFacebook: "https://facebook.com/bemmaisbella/posts/saude-2026",
    urlInstagram: "https://instagram.com/p/saude2026/",
    urlTikTok: "https://tiktok.com/@bemmaisbella/video/saude2026",
    urlPinterest: "https://pinterest.com/pin/saude2026",
    palavraChave: "saude feminina 2026 cuidados",
    metaDescription: "10 cuidados essenciais para a saúde feminina em 2026.",
    status: "Publicado",
  },
  {
    slug: "cartilha-pos-parto-usp-2026",
    title: "USP Lança Cartilha de Planejamento do Pós-Parto",
    categoria: "Maternidade e Família",
    subcategoria: "Pós-Parto",
    data: "2026-08-03",
    autor: "Lillith Nogah",
    descricao: "Pesquisadoras da USP lançam primeira cartilha brasileira de planejamento do pós-parto.",
    urlSite: "https://bemmaisbella.com.br/maternidade-e-familia/pos-parto/cartilha-usp",
    urlFacebook: "https://facebook.com/bemmaisbella/posts/cartilha-usp",
    urlInstagram: "https://instagram.com/p/cartilhausp/",
    urlTikTok: "https://tiktok.com/@bemmaisbella/video/cartilhausp",
    urlPinterest: "https://pinterest.com/pin/cartilhausp",
    palavraChave: "cartilha pos parto usp",
    metaDescription: "Cartilha inédita da USP orienta gestantes sobre recuperação, vínculo e bem-estar materno.",
    status: "Publicado",
  },
  {
    slug: "reder-mulher-empreendedora-2026",
    title: "Rede Mulher Empreendedora: Liderança Feminina",
    categoria: "Carreira e Finanças",
    subcategoria: "Carreira com Propósito",
    data: "2026-08-04",
    autor: "Lillith Nogah",
    descricao: "Núcleo Estratégico reforça empreendedorismo feminino — investimentos, liderança, finanças.",
    urlSite: "https://bemmaisbella.com.br/carreira-e-financas/empreendedorismo/2026",
    urlFacebook: "https://facebook.com/bemmaisbella/posts/empreendedorismo2026",
    urlInstagram: "https://instagram.com/p/emp2026/",
    urlTikTok: "https://tiktok.com/@bemmaisbella/video/emp2026",
    urlPinterest: "https://pinterest.com/pin/emp2026",
    palavraChave: "empreendedorismo feminino 2026",
    metaDescription: "Rede Mulher Empreendedora e Núcleo Estratégico — liderança feminina no Brasil.",
    status: "Publicado",
  },
  {
    slug: "leis-protecao-mulheres-lula-2026",
    title: "Lula Sanciona Três Leis que Ampliam Proteção às Mulheres",
    categoria: "Histórias Inspiradoras",
    subcategoria: "Superação",
    data: "2026-08-05",
    autor: "Lillith Nogah",
    descricao: "Três novas leis ampliam proteção às mulheres — marco para direitos femininos.",
    urlSite: "https://bemmaisbella.com.br/historias-inspiradoras/leis-protecao-2026",
    urlFacebook: "https://facebook.com/bemmaisbella/posts/leis-2026",
    urlInstagram: "https://instagram.com/p/leis2026/",
    urlTikTok: "https://tiktok.com/@bemmaisbella/video/leis2026",
    urlPinterest: "https://pinterest.com/pin/leis2026",
    palavraChave: "leis protecao mulheres 2026",
    metaDescription: "Novas leis ampliam proteção às mulheres no Brasil — marco histórico.",
    status: "Publicado",
  },
];

export const artigosPublicados = NOTICIAS_MOCK.filter(n => n.status === "Publicado");
export const artigosRascunho = NOTICIAS_MOCK.filter(n => n.status === "Rascunho");
